package netgloo.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by wscown on 3/4/16.
 */
@Entity
@Table(name = "accounts")
public class Account {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    @NotNull
    private String _id;

    @NotNull
    private String type;

    @NotNull
    private String nickname;

    @NotNull
    private int rewards;

    @NotNull
    private double balance;

    @NotNull
    private String username;

    //User ID (to link with the user)
    private String customer_id;

    // Public methods

    public Account() { }

    public Account(long id) {
        this.id = id;
    }

    public Account(String _id, String type, String nickname, int rewards, double balance, String username) {
        this._id = _id;
        this.type = type;
        this.nickname = nickname;
        this.rewards = rewards;
        this.balance = balance;
        this.username = username;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String get_id() {
        return _id;
    }

    public void set_id(String _id) {
        this._id = _id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public int getRewards() {
        return rewards;
    }

    public void setRewards(int rewards) {
        this.rewards = rewards;
    }

    public double getBalance() {
        return balance;
    }

    public void setBalance(double balance) {
        this.balance = balance;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getCustomer_id() {
        return customer_id;
    }

    public void setCustomer_id(String customer_id) {
        this.customer_id = customer_id;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }
}
