package netgloo.models;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by wscown on 3/4/16.
 */
@Entity
@Table(name = "accounts")
public class Account {

    // An autogenerated id (unique for each user in the db)

    /*@GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
*/


    @NotNull
    @Transient
    private String type;


    @NotNull
    @Transient
    private String nickname;

    @NotNull
    @Transient
    private int rewards;

    @NotNull
    @Transient
    private double balance;

    //User ID (to link with the user)
    @NotNull
    private String customer_id;

    @Id
    @NotNull
    private String _id;

    @JsonIgnore
    @NotNull
    private double goal;

    // Public methods

    public Account() { }

/*    public Account(long id) {
        this.id = id;
    }
*/
    public Account(String type, String nickname, int rewards, double balance){
        this.type = type;
        this.nickname = nickname;
        this.rewards = rewards;
        this.balance = balance;
        //this.customer_id = customer_id;
    }

    public Account(String _id,  String nickname) {
        this._id = _id;
        this.nickname = nickname;

    }

  /*  public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }*/

    public String get_id() {
        return _id;
    }

    public void set_id(String _id) {
        this._id = _id;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public int getRewards() {
        return rewards;
    }

    public void setRewards(int rewards) {
        this.rewards = rewards;
    }

    public double getBalance() {
        return balance;
    }

    public void setBalance(double balance) {
        this.balance = balance;
    }

    public String getCustomer_id() {
        return customer_id;
    }

    public void setCustomer_id(String customer_id) {
        this.customer_id = customer_id;
    }

    public double getGoal() {
        return goal;
    }

    public void setGoal(double goal) {
        this.goal = goal;
    }
}
