package netgloo.models;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by wscown on 3/4/16.
 */
@Entity
@Table(name = "users")
public class User {

    // An autogenerated id (unique for each user in the db)

    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    @Id
    @NotNull
    private String username;

    @NotNull
    private String password;

    @NotNull
    private String customerId;

    // Public methods


    public User() { }

    public User(long id) {
        this.id = id;
    }

    public User(String username, String password, String customerId) {
        this.username = username;
        this.password = password;
        this.customerId = customerId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword() {
        return password;
    }

    public boolean checkPassword(String password){
        return password.equals(this.password);
    }
}